apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-httpd-pod
  namespace: test

spec:
  selector:
    matchLabels:
      app: httpd-web
      location: IN
      environment: Production
      tier: frontend
  replicas: 1
  template:
    metadata:
      name: httpd-pod
      namespace: test
      labels:
        app: httpd-web
        location: IN
        environment: Production
        tier: frontend

    spec:
      containers:
      - name: httpd-web
        #image: pawanitzone/gke-image:35
        image: 260699962226.dkr.ecr.ap-south-1.amazonaws.com/argocd:latest
        volumeMounts:
            - name: httpd-volume
              mountPath: /opt
      volumes:
        - name: httpd-volume
          persistentVolumeClaim:
            claimName: httpd-pvc
